services:
  - type: db
    name: sim-db
    databaseName: simstudio
    user: simstudio
    plan: free

  - type: redis
    name: sim-redis
    plan: free

  - type: web
    name: sim-studio
    plan: starter # Your $7 plan
    repo: https://github.com/aliq99/simQ99
    dockerContext: ./packages/studio
    dockerfilePath: ./packages/studio/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: db
          name: sim-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sim-redis
          property: connectionString
