databases:
  - name: sim-database
    databaseName: simstudio
    user: simstudio
    plan: free

services:
  - type: redis
    name: sim-redis
    plan: free

  - type: web
    name: sim-studio
    plan: starter
    repo: https://github.com/aliq99/simQ99
    dockerContext: ./packages/studio
    dockerfilePath: ./packages/studio/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sim-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: sim-redis
          property: connectionString
